[2022-06-02 16:20:55,326] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:20:55,326] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:20:55,327] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,327] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:20:55,354] {processor.py:651} INFO - DAG(s) dict_keys(['TRAVELOKA_V1']) retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:20:55,685] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,685] {manager.py:508} INFO - Created Permission View: can delete on DAG:TRAVELOKA_V1
[2022-06-02 16:20:55,710] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,710] {manager.py:508} INFO - Created Permission View: can read on DAG:TRAVELOKA_V1
[2022-06-02 16:20:55,723] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,723] {manager.py:508} INFO - Created Permission View: can edit on DAG:TRAVELOKA_V1
[2022-06-02 16:20:55,724] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,724] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-02 16:20:55,739] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,738] {dag.py:2398} INFO - Creating ORM DAG for TRAVELOKA_V1
[2022-06-02 16:20:55,764] {logging_mixin.py:115} INFO - [2022-06-02 16:20:55,764] {dag.py:2927} INFO - Setting next_dagrun for TRAVELOKA_V1 to 2022-06-01T00:00:00+00:00, run_after=2022-06-02T00:00:00+00:00
[2022-06-02 16:20:55,786] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.464 seconds
[2022-06-02 16:21:25,880] {processor.py:153} INFO - Started process (PID=74) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:21:25,882] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:21:25,883] {logging_mixin.py:115} INFO - [2022-06-02 16:21:25,883] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:21:25,905] {processor.py:651} INFO - DAG(s) dict_keys(['TRAVELOKA_V1']) retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:21:25,935] {logging_mixin.py:115} INFO - [2022-06-02 16:21:25,935] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-02 16:21:26,068] {logging_mixin.py:115} INFO - [2022-06-02 16:21:26,068] {dag.py:2927} INFO - Setting next_dagrun for TRAVELOKA_V1 to 2022-06-01T00:00:00+00:00, run_after=2022-06-02T00:00:00+00:00
[2022-06-02 16:21:26,081] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.209 seconds
[2022-06-02 16:21:56,170] {processor.py:153} INFO - Started process (PID=94) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:21:56,172] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:21:56,173] {logging_mixin.py:115} INFO - [2022-06-02 16:21:56,173] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:21:56,195] {processor.py:651} INFO - DAG(s) dict_keys(['TRAVELOKA_V1']) retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:21:56,227] {logging_mixin.py:115} INFO - [2022-06-02 16:21:56,227] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-02 16:21:56,370] {logging_mixin.py:115} INFO - [2022-06-02 16:21:56,370] {dag.py:2927} INFO - Setting next_dagrun for TRAVELOKA_V1 to 2022-06-01T00:00:00+00:00, run_after=2022-06-02T00:00:00+00:00
[2022-06-02 16:21:56,383] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.223 seconds
[2022-06-02 16:21:58,424] {processor.py:153} INFO - Started process (PID=96) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:21:58,425] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:21:58,427] {logging_mixin.py:115} INFO - [2022-06-02 16:21:58,427] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:21:58,446] {processor.py:651} INFO - DAG(s) dict_keys(['TRAVELOKA_V1']) retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:21:58,646] {logging_mixin.py:115} INFO - [2022-06-02 16:21:58,646] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-02 16:21:58,677] {logging_mixin.py:115} INFO - [2022-06-02 16:21:58,677] {dag.py:2927} INFO - Setting next_dagrun for TRAVELOKA_V1 to 2022-06-02T00:00:00+00:00, run_after=2022-06-03T00:00:00+00:00
[2022-06-02 16:21:58,697] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.283 seconds
[2022-06-02 16:22:02,423] {processor.py:153} INFO - Started process (PID=107) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:22:02,424] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:22:02,424] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,424] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:22:02,435] {processor.py:651} INFO - DAG(s) dict_keys(['FOODY_V1']) retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:22:02,640] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,640] {manager.py:508} INFO - Created Permission View: can delete on DAG:FOODY_V1
[2022-06-02 16:22:02,652] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,652] {manager.py:508} INFO - Created Permission View: can read on DAG:FOODY_V1
[2022-06-02 16:22:02,661] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,661] {manager.py:508} INFO - Created Permission View: can edit on DAG:FOODY_V1
[2022-06-02 16:22:02,661] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,661] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-02 16:22:02,670] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,670] {dag.py:2398} INFO - Creating ORM DAG for FOODY_V1
[2022-06-02 16:22:02,686] {logging_mixin.py:115} INFO - [2022-06-02 16:22:02,686] {dag.py:2927} INFO - Setting next_dagrun for FOODY_V1 to 2022-06-02T00:00:00+00:00, run_after=2022-06-03T00:00:00+00:00
[2022-06-02 16:22:02,700] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.280 seconds
[2022-06-02 16:24:17,462] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:24:17,463] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:24:17,464] {logging_mixin.py:115} INFO - [2022-06-02 16:24:17,464] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:24:17,483] {logging_mixin.py:115} INFO - [2022-06-02 16:24:17,482] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:24:17,483] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:24:17,509] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.051 seconds
[2022-06-02 16:24:47,548] {processor.py:153} INFO - Started process (PID=70) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:24:47,550] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:24:47,550] {logging_mixin.py:115} INFO - [2022-06-02 16:24:47,550] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:24:47,562] {logging_mixin.py:115} INFO - [2022-06-02 16:24:47,561] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:24:47,563] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:24:47,590] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.047 seconds
[2022-06-02 16:25:15,644] {processor.py:153} INFO - Started process (PID=92) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:25:15,644] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:25:15,645] {logging_mixin.py:115} INFO - [2022-06-02 16:25:15,644] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:25:15,658] {logging_mixin.py:115} INFO - [2022-06-02 16:25:15,656] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:25:15,658] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:25:15,682] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.042 seconds
[2022-06-02 16:25:45,743] {processor.py:153} INFO - Started process (PID=112) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:25:45,744] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:25:45,745] {logging_mixin.py:115} INFO - [2022-06-02 16:25:45,744] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:25:45,755] {logging_mixin.py:115} INFO - [2022-06-02 16:25:45,754] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:25:45,755] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:25:45,773] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.032 seconds
[2022-06-02 16:31:03,346] {processor.py:153} INFO - Started process (PID=48) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:31:03,347] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:31:03,348] {logging_mixin.py:115} INFO - [2022-06-02 16:31:03,348] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:31:03,376] {logging_mixin.py:115} INFO - [2022-06-02 16:31:03,374] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:31:03,376] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:31:03,469] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.127 seconds
[2022-06-02 16:31:33,574] {processor.py:153} INFO - Started process (PID=70) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:31:33,574] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:31:33,575] {logging_mixin.py:115} INFO - [2022-06-02 16:31:33,575] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:31:33,584] {logging_mixin.py:115} INFO - [2022-06-02 16:31:33,583] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:31:33,584] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:31:33,605] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.033 seconds
[2022-06-02 16:32:03,706] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:32:03,707] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:32:03,707] {logging_mixin.py:115} INFO - [2022-06-02 16:32:03,707] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:32:03,717] {logging_mixin.py:115} INFO - [2022-06-02 16:32:03,716] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:32:03,717] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:32:03,739] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.036 seconds
[2022-06-02 16:32:33,807] {processor.py:153} INFO - Started process (PID=128) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:32:33,808] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:32:33,808] {logging_mixin.py:115} INFO - [2022-06-02 16:32:33,808] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:32:33,817] {logging_mixin.py:115} INFO - [2022-06-02 16:32:33,816] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:32:33,818] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:32:33,837] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.033 seconds
[2022-06-02 16:33:03,918] {processor.py:153} INFO - Started process (PID=149) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:33:03,920] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:33:03,921] {logging_mixin.py:115} INFO - [2022-06-02 16:33:03,921] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:33:03,939] {logging_mixin.py:115} INFO - [2022-06-02 16:33:03,938] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:33:03,939] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:33:03,962] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.052 seconds
[2022-06-02 16:33:33,995] {processor.py:153} INFO - Started process (PID=179) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:33:33,996] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:33:33,997] {logging_mixin.py:115} INFO - [2022-06-02 16:33:33,997] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:33:34,011] {logging_mixin.py:115} INFO - [2022-06-02 16:33:34,010] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:33:34,011] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:33:34,039] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.048 seconds
[2022-06-02 16:34:04,111] {processor.py:153} INFO - Started process (PID=200) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:34:04,111] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:34:04,112] {logging_mixin.py:115} INFO - [2022-06-02 16:34:04,112] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:34:04,122] {logging_mixin.py:115} INFO - [2022-06-02 16:34:04,121] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:34:04,122] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:34:04,182] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.074 seconds
[2022-06-02 16:34:34,262] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:34:34,263] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:34:34,263] {logging_mixin.py:115} INFO - [2022-06-02 16:34:34,263] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:34:34,276] {logging_mixin.py:115} INFO - [2022-06-02 16:34:34,275] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:34:34,276] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:34:34,302] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.043 seconds
[2022-06-02 16:35:04,338] {processor.py:153} INFO - Started process (PID=250) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:35:04,339] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:35:04,339] {logging_mixin.py:115} INFO - [2022-06-02 16:35:04,339] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:35:04,352] {logging_mixin.py:115} INFO - [2022-06-02 16:35:04,351] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:35:04,352] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:35:04,377] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.043 seconds
[2022-06-02 16:35:34,436] {processor.py:153} INFO - Started process (PID=280) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:35:34,437] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:35:34,438] {logging_mixin.py:115} INFO - [2022-06-02 16:35:34,437] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:35:34,449] {logging_mixin.py:115} INFO - [2022-06-02 16:35:34,448] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:35:34,449] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:35:34,473] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.040 seconds
[2022-06-02 16:36:04,518] {processor.py:153} INFO - Started process (PID=301) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:36:04,519] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:36:04,520] {logging_mixin.py:115} INFO - [2022-06-02 16:36:04,520] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:36:04,550] {logging_mixin.py:115} INFO - [2022-06-02 16:36:04,548] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:36:04,550] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:36:04,574] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.059 seconds
[2022-06-02 16:36:34,645] {processor.py:153} INFO - Started process (PID=331) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:36:34,647] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:36:34,647] {logging_mixin.py:115} INFO - [2022-06-02 16:36:34,647] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:36:34,659] {logging_mixin.py:115} INFO - [2022-06-02 16:36:34,658] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:36:34,660] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:36:34,683] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.042 seconds
[2022-06-02 16:36:35,670] {processor.py:153} INFO - Started process (PID=333) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:36:35,671] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:36:35,672] {logging_mixin.py:115} INFO - [2022-06-02 16:36:35,672] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:36:35,694] {logging_mixin.py:115} INFO - [2022-06-02 16:36:35,693] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:36:35,695] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:36:35,719] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.058 seconds
[2022-06-02 16:37:05,799] {processor.py:153} INFO - Started process (PID=363) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:37:05,800] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:37:05,800] {logging_mixin.py:115} INFO - [2022-06-02 16:37:05,800] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:05,810] {logging_mixin.py:115} INFO - [2022-06-02 16:37:05,809] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:37:05,810] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:05,830] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.034 seconds
[2022-06-02 16:37:17,874] {processor.py:153} INFO - Started process (PID=374) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:37:17,875] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:37:17,875] {logging_mixin.py:115} INFO - [2022-06-02 16:37:17,875] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:17,886] {logging_mixin.py:115} INFO - [2022-06-02 16:37:17,885] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:37:17,886] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:17,909] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.038 seconds
[2022-06-02 16:37:18,849] {processor.py:153} INFO - Started process (PID=377) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:37:18,850] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:37:18,850] {logging_mixin.py:115} INFO - [2022-06-02 16:37:18,850] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:18,861] {logging_mixin.py:115} INFO - [2022-06-02 16:37:18,860] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:37:18,861] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:18,882] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.036 seconds
[2022-06-02 16:37:48,939] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:37:48,940] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:37:48,941] {logging_mixin.py:115} INFO - [2022-06-02 16:37:48,941] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:48,954] {logging_mixin.py:115} INFO - [2022-06-02 16:37:48,953] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:37:48,954] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:37:48,980] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.045 seconds
[2022-06-02 16:38:19,020] {processor.py:153} INFO - Started process (PID=427) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:38:19,021] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:38:19,022] {logging_mixin.py:115} INFO - [2022-06-02 16:38:19,022] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:38:19,035] {logging_mixin.py:115} INFO - [2022-06-02 16:38:19,034] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:38:19,035] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:38:19,062] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.045 seconds
[2022-06-02 16:41:16,490] {processor.py:153} INFO - Started process (PID=47) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:41:16,492] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:41:16,492] {logging_mixin.py:115} INFO - [2022-06-02 16:41:16,492] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:41:16,520] {logging_mixin.py:115} INFO - [2022-06-02 16:41:16,519] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:41:16,520] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:41:16,553] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.067 seconds
[2022-06-02 16:41:46,651] {processor.py:153} INFO - Started process (PID=68) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:41:46,652] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:41:46,653] {logging_mixin.py:115} INFO - [2022-06-02 16:41:46,653] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:41:46,668] {logging_mixin.py:115} INFO - [2022-06-02 16:41:46,667] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:41:46,669] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:41:46,693] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.052 seconds
[2022-06-02 16:42:16,779] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/test/test.py
[2022-06-02 16:42:16,781] {processor.py:641} INFO - Processing file /opt/airflow/dags/test/test.py for tasks to queue
[2022-06-02 16:42:16,782] {logging_mixin.py:115} INFO - [2022-06-02 16:42:16,782] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test/test.py
[2022-06-02 16:42:16,799] {logging_mixin.py:115} INFO - [2022-06-02 16:42:16,798] {dagbag.py:412} ERROR - Failed to bag_dag: /opt/airflow/dags/test/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 173, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 166, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 774, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/croniter/croniter.py", line 620, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 405, in _process_modules
    dag.timetable.validate()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/timetables/interval.py", line 175, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2022-06-02 16:42:16,799] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test.py
[2022-06-02 16:42:16,822] {processor.py:161} INFO - Processing /opt/airflow/dags/test/test.py took 0.053 seconds
